quarkus.application.name=emprestimo-service
quarkus.http.port=8081
quarkus.rest-client.feriado-api.url=https://brasilapi.com.br
quarkus.rest-client.feriado-api.connect-timeout=3000
quarkus.rest-client.feriado-api.read-timeout=3000
