quarkus.application.name=emprestimo-service
quarkus.http.port=8081
quarkus.rest-client.feriado-api.url=https://brasilapi.com.br
quarkus.rest-client.feriado-api.connect-timeout=3000
quarkus.rest-client.feriado-api.read-timeout=3000
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=14
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/biblioteca
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%prod.quarkus.datasource.jdbc.url=${EMPRESTIMO_DB_URL}
%prod.quarkus.datasource.username=${EMPRESTIMO_DB_USERNAME}
%prod.quarkus.datasource.password=${EMPRESTIMO_DB_PASSWORD}
